---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: traefik-acme
  namespace: traefik-system
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50M
