apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
  annotations:
    metallb.universe.tf/address-pool: internal
spec:
  type: LoadBalancer   
  ports:
    - protocol: TCP
      name: websecure
      port: 443
    - protocol: TCP
      name: web
      port: 80
    - name: mariadb
      port: 3306
    - name: postgres
      port: 5432
    - name: mssql
      port: 1433
    - name: mongodb
      port: 27017
  selector:
    app: traefik
