apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik-system
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  type: LoadBalancer   
  ports:
    - protocol: TCP
      name: websecure
      port: 443
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: traefik
